#!/bin/bash
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.53.242:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.55.65:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.54.195:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.54.130:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.54.161:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.52.109:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.53.166:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.54.214:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.53.12:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.53.24:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.52.138:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.1.31:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.1.42:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.1.216:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.1.92:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.1.10:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.1.39:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.1.182:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.1.23:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.1.119:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.1.22:
rsync -avz /Users/ramesh_ayyagari/Projects/nat-scale/scale-clojure-web-app ec2-user@10.0.1.174:
